services:
  credibanco:
    build:
      context: ../
      dockerfile: credibanco-mssql/Dockerfile
    image: gustavo0426/api-microservice-credibanco:1.0.0
    container_name: credibanco
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9091:9091"
    depends_on:
      - mssql

  mssql:
    build:
      context: docker_mssql
      dockerfile: Dockerfile
    image: gustavo0426/mssql-db:1.0.0
    container_name: mssql
    restart: always
    volumes:
      - mssql-db:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
volumes:
  mssql-db: