services:
  credibanco:
    build:
      context: ../
      dockerfile: credibanco-mssql/Dockerfile
    container_name: credibanco
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - 9091:${SERVER_PORT}
    depends_on:
      - mssql

  mssql:
    build:
      context: docker_mssql
      dockerfile: Dockerfile
    container_name: mssql
    restart: always
    volumes:
      - mssql-db:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 1010:${DB_PORT}
volumes:
  mssql-db: