services:
  credibanco:
    build:
      context: ../
      dockerfile: credibanco-mssql/Dockerfile
    container_name: credibanco
    restart: always
    networks:
      - dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${PORT}
    ports:
      - "9091:${PORT}"
    depends_on:
      - mssql

  mssql:
    build:
      context: docker-mssql
      dockerfile: Dockerfile
    container_name: mssql
    restart: always
    networks:
      - dev
    volumes:
      - mssql-db:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
networks:
  dev:
volumes:
  mssql-db: