version: "3.9"

services:
  credibanco:
    build:
      context: ../
      dockerfile: credibanco-mssql/Dockerfile
    container_name: credibanco
    environment:
      DB_HOST: "mssql"
      DB_PORT: "1433"
      DB_DATABASE: "HelloWorld"
      DB_USERNAME: "sa"
      DB_PASSWORD: "MSSQLServer2311*"
    ports:
      - "9091:9091"
    depends_on:
      - mssql

  mssql:
    build:
      context: docker_mssql
      dockerfile: Dockerfile
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MSSQLServer2311*"
    ports:
      - "1433:1433"