spring:
  profiles:
    active: "dev"
---
spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:192.168.80.17}:${DB_PORT:1433};databaseName=${DB_DATABASE:credibancodb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
server:
  port: ${SERVER_PORT:9091}